// <auto-generated />
using System;
using Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coffe.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    [Migration("20260511165019_InititalCreate")]
    partial class InititalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.BatchCoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_producer_id");

                    b.Property<int>("CoffeeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_type_id");

                    b.Property<int?>("CoffeeVarietyId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_variety_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("humidity");

                    b.Property<decimal>("ScoreSCA")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("score_sca");

                    b.Property<decimal>("ScreenSize")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("screen_size");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeProducerId");

                    b.HasIndex("CoffeeTypeId");

                    b.HasIndex("CoffeeVarietyId");

                    b.ToTable("batch_coffee_producer");
                });

            modelBuilder.Entity("Domain.Entity.CoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(140)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(140)")
                        .HasColumnName("lastname");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("coffee_producer");
                });

            modelBuilder.Entity("Domain.Entity.CoffeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("coffee_type");
                });

            modelBuilder.Entity("Domain.Entity.CoffeeVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("coffee_variety");
                });

            modelBuilder.Entity("Domain.Entity.DetailPurchaseCoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchCoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("batch_coffee_producer_id");

                    b.Property<int>("CoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_producer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PurchaseCoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_coffee_producer_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchCoffeeProducerId");

                    b.HasIndex("CoffeeProducerId");

                    b.HasIndex("PurchaseCoffeeProducerId");

                    b.ToTable("detail_purchase_coffee_producer");
                });

            modelBuilder.Entity("Domain.Entity.MeasurementUnitCoffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("measurement_unit_coffee");
                });

            modelBuilder.Entity("Domain.Entity.PurchaseBatchCoffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("amount");

                    b.Property<int>("BatchCoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("batch_coffee_producer_id");

                    b.Property<decimal>("BatchPurchasePrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("batch_purchase_price");

                    b.Property<decimal>("CoffeeMarketPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("coffee_market_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("ExpectedBatchSellingPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("expected_batch_selling_price");

                    b.Property<int>("MeasurementUnitCoffeeId")
                        .HasColumnType("int")
                        .HasColumnName("measurement_unit_coffee_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchCoffeeProducerId")
                        .IsUnique();

                    b.HasIndex("MeasurementUnitCoffeeId");

                    b.ToTable("purchase_batch_coffee");
                });

            modelBuilder.Entity("Domain.Entity.PurchaseCoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_producer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeProducerId");

                    b.ToTable("purchase_coffee_producer");
                });

            modelBuilder.Entity("Domain.Entity.BatchCoffeeProducer", b =>
                {
                    b.HasOne("Domain.Entity.CoffeeProducer", "Producer")
                        .WithMany("Batches")
                        .HasForeignKey("CoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.CoffeeType", "CoffeeType")
                        .WithMany()
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.CoffeeVariety", "CoffeeVariety")
                        .WithMany()
                        .HasForeignKey("CoffeeVarietyId");

                    b.Navigation("CoffeeType");

                    b.Navigation("CoffeeVariety");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entity.DetailPurchaseCoffeeProducer", b =>
                {
                    b.HasOne("Domain.Entity.BatchCoffeeProducer", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchCoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.CoffeeProducer", "Producer")
                        .WithMany()
                        .HasForeignKey("CoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.PurchaseCoffeeProducer", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseCoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Producer");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Domain.Entity.PurchaseBatchCoffee", b =>
                {
                    b.HasOne("Domain.Entity.BatchCoffeeProducer", "Batch")
                        .WithOne("Purchase")
                        .HasForeignKey("Domain.Entity.PurchaseBatchCoffee", "BatchCoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.MeasurementUnitCoffee", "MeasurementUnitCoffee")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitCoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("MeasurementUnitCoffee");
                });

            modelBuilder.Entity("Domain.Entity.PurchaseCoffeeProducer", b =>
                {
                    b.HasOne("Domain.Entity.CoffeeProducer", "Producer")
                        .WithMany("Purchases")
                        .HasForeignKey("CoffeeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entity.BatchCoffeeProducer", b =>
                {
                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Domain.Entity.CoffeeProducer", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
