// <auto-generated />
using System;
using Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coffe.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    partial class CoffeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.BatchCoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeProducerId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_producer_id");

                    b.Property<int>("CoffeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CoffeVarietyId")
                        .HasColumnType("int");

                    b.Property<int>("CoffeeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_type_id");

                    b.Property<int?>("CoffeeVarietyId")
                        .HasColumnType("int")
                        .HasColumnName("coffee_variety_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("humidity");

                    b.Property<decimal>("ScoreSCA")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("score_sca");

                    b.Property<decimal>("ScreenSize")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("screen_size");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoffeProducerId");

                    b.HasIndex("CoffeTypeId");

                    b.HasIndex("CoffeVarietyId");

                    b.ToTable("batch_coffee_producer", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.CoffeeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(140)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(140)")
                        .HasColumnName("lastname");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("coffee_producer", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.CoffeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("coffee_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.CoffeeVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("coffee_variety", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.BatchCoffeeProducer", b =>
                {
                    b.HasOne("Domain.Entity.CoffeeProducer", "Producer")
                        .WithMany("Batches")
                        .HasForeignKey("CoffeProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.CoffeeType", "CoffeeType")
                        .WithMany()
                        .HasForeignKey("CoffeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.CoffeeVariety", "CoffeeVariety")
                        .WithMany()
                        .HasForeignKey("CoffeVarietyId");

                    b.Navigation("CoffeeType");

                    b.Navigation("CoffeeVariety");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Domain.Entity.CoffeeProducer", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
