:BASE_URL = http://localhost:5274
:COFFEE_PRODUCER_URL = :BASE_URL/api/coffee-producer

GET :COFFEE_PRODUCER_URL/1
Accept: application/json

###

PUT :COFFEE_PRODUCER_URL/1
Content-Type: application/json
{
    "Id": 3,
    "FirstName": "Maria",
    "LastName": "Suarez",
    "DocumentNumber": "23434"
}

###

GET :COFFEE_PRODUCER_URL/list/?PageSize=10&PageNumber=1
Accept: application/json

###

POST http://localhost:5274/api/coffee-producer
Content-Type: application/json
{
    "FirstName": "Manuel",
    "LastName": "Salas",
    "DocumentNumber": "81236"
}

###

DELETE :COFFEE_PRODUCER_URL/1
Accept: application/json

###
